#Constantes de Tempo
SIMULATION_TIME = 720
CYCLE_TIME = 60
OFFSET = 10
IGNORECYCLES = 2
YELLOW_TIME = 2
MINFASE_TIME = 2
LIGHTSID = ["A","B"]

#Contantes Geneticas
MAXPOPULATION = 20
MAXGENERATIONS = 10
MUTATIONRATE = 0.3
MUTATIONGENERATE = 0.05
CREATEGUY = 1

